version: 2.1

orbs:
  node: circleci/node@3.0.1

jobs:
  build:
    docker:
      - image: buildpack-deps:trusty # primary container
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
        environment:
          ENV: CI
    executor: node/default
    steps:
      - checkout
      - node/install-npm
      - node/install-packages:
          app-dir: ~/backend_api
          cache-path: node_modules
          override-ci-command: npm i

workflows:
  version: 2
  build_and_test:
    jobs:
      - build

