version: 2.1

orbs:
  node: circleci/node@4.7.0

jobs:
  buildImage:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      # build the application image
     - run: docker build . -t nodeappimage
     # deploy the image
     - run: docker run -p 1444:8080 nodeappimage
     - run: curl localhost:1444
workflows:
  version: 2
  build:
    jobs:
      - buildImage