version: 2.1
  jobs:
    jobs:
      build:
        executor: node/default
        steps:
          - checkout
          - node/install-npm
          - node/install-packages:
              cache-path: node_modules
              override-ci-command: npm i
          - persist_to_workspace:
              root: .
              paths:
                - .

      test:
        docker:
          - image: nodejsapp
        steps:
          - attach_workspace:
              at: .
          - run:
              name: Test
              command: npm test

workflows:
  version: 2
    test_build:
      jobs:
          - test
            - build:
            requires:
              - test
