version: 2.1

orbs:
  node: circleci/node@4.7.0

jobs:
  runApp:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/node-js-sample-master/node_modules
          override-ci-command: npm install
      - run: npm start &
  buildImage:
    machine: true
    steps:
      # build the application image
     - run: docker build . -t nodeappimage
     # deploy the image
     - run: docker push nodeappimage
workflows:
  version: 2
  build:
    jobs:
      - buildImage
      - runApp:
          requires:
            - buildImage